# 📊 BÀI TẬP PHÂN TÍCH DỮ LIỆU VIỆT NAM JOBS
*Người thực hiện: Oanh Vi*
*Mục đích: Luyện tập các kỹ năng cơ bản về Pandas, làm sạch chuỗi và trực quan hóa dữ liệu tuyển dụng tại Việt Nam.*

In [1]:
from google.colab import files
uploaded = files.upload()

Saving vietnam_jobs.csv to vietnam_jobs (1).csv

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Đọc file dữ liệu với cấu hình font tiếng Việt
vietnam_jobs = pd.read_csv('vietnam_jobs.csv')

# Hiển thị thông tin tổng quan
# Hiển thị 25 dòng đầu tiên
vietnam_jobs.head(25)

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit
0,trưởng phòng kinh doanh,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,lên đến 1 năm,NaN,"kinh doanh, bán hàng, nội ngoại thất, xây dựng",15 tr - 50 tr vnd,15.0,50.0,vnd
1,nhân viên qc ngành cơ khí,nhân viên chính thức,nhân viên,hồ chí minh,trên 1 năm,"production planning staff, chuyên viên iso, th...","vận hành sản xuất, sản xuất, qc), quản lý chất...",8 tr - 11 tr vnd,8.0,11.0,vnd
2,trưởng phòng đấu thầu,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,5 - 7 năm,"trưởng phòng xây dựng, trưởng phòng đấu thầu, ...","điện, xây dựng, điện tử, điện lạnh, dầu khí, đ...",20 tr - 30 tr vnd,20.0,30.0,vnd
3,home textile designer,nhân viên chính thức,nhân viên,hưng yên,5 - 15 năm,NaN,"dệt may, nghệ thuật, da giày, thiết kế, mỹ thu...","800 - 1,500 usd",20.0,37.5,usd
4,nhân viên kinh doanh,nhân viên chính thức,nhân viên,hồ chí minh,trên 1 năm,NaN,"tư vấn, bán sỉ, bán lẻ, kinh doanh, bán hàng",10 tr - 50 tr vnd,10.0,50.0,vnd
5,giám đốc kinh doanh khu vực kem dẻo thổ nhĩ kỳ...,nhân viên chính thức,quản lý,bình định,2 - 5 năm,"sales director, giám đốc kinh doanh khu vực ke...","thực phẩm & đồ uống, bán sỉ, bán lẻ, kinh doan...",15 tr - 40 tr vnd,15.0,40.0,vnd
6,chuyên viên kinh doanh bất động sản,nhân viên chính thức,nhân viên,hà nội,lên đến 1 năm,"bất động sản, chuyên viên kinh doanh, bđs, rea...",bất động sản,15 tr - 50 tr vnd,15.0,50.0,vnd
7,kỹ thuật viên ie,nhân viên chính thức,nhân viên,hà nam,chưa có kinh nghiệm,kỹ thuật viên ie tiếng trung,"vận hành sản xuất, sản xuất",10 tr - 18 tr vnd,10.0,18.0,vnd
8,kế toán tổng hợp,nhân viên chính thức,nhân viên,bến tre,3 - 5 năm,"kế toán tổng hợp, nhân viên kế toán tổng hợp, ...","kế toán, kiểm toán, xuất nhập khẩu, vận hành s...",15 tr - 20 tr vnd,15.0,20.0,vnd
9,quản lý nhãn hàng,nhân viên chính thức,"trưởng nhóm , giám sát",hà nội,trên 2 năm,quản lý nhãn hàng,"marketing, y tế, dược phẩm, thẩm mỹ, hóa mỹ ph...",17 tr - 22 tr vnd,17.0,22.0,vnd
10,hr admin executive chuyên viên hành chính nhân sự,nhân viên chính thức,nhân viên,hà nội,không yêu cầu,NaN,"thư ký, hành chính, giao nhận, vận chuyển, nhâ...","9,5 tr - 12 tr vnd",9.5,12.0,vnd
11,trưởng nhóm digital marketing,nhân viên chính thức,quản lý,hồ chí minh,2 - 25 năm,"online, digital marketer, trưởng nhóm digital ...","marketing, truyền thông, cơ khí, đối ngoại, qu...",14 tr - 25 tr vnd,14.0,25.0,vnd
12,kỹ sư kinh tế xây dựng,nhân viên chính thức,nhân viên,hà nội,3 - 5 năm,NaN,xây dựng,15 tr - 18 tr vnd,15.0,18.0,vnd
13,nhân viên điều phối vật tư,nhân viên chính thức,nhân viên,hồ chí minh,1 - 3 năm,NaN,"giao nhận, vận chuyển, kho vận",8 tr - 10 tr vnd,8.0,10.0,vnd
14,nhân viên kinh doanh,nhân viên chính thức,nhân viên,hồ chí minh,2 - 5 năm,NaN,"y tế, dược phẩm, thẩm mỹ, hóa mỹ phẩm, làm đẹp...",12 tr - 15 tr vnd,12.0,15.0,vnd
15,kinh doanh quốc tế,nhân viên chính thức,nhân viên,hồ chí minh,2 - 5 năm,NaN,"kinh doanh, bán hàng, xuất nhập khẩu, biên phi...",25 tr - 30 tr vnd,25.0,30.0,vnd
16,retail associate nhân viên bán hàng,nhân viên chính thức,nhân viên,hồ chí minh,1 - 3 năm,"store manager, operation manager, sales staff,...","nhà hàng, bán sỉ, bán lẻ, kinh doanh, bán hàng...",10 tr - 15 tr vnd,10.0,15.0,vnd
17,nhân viên telesale,nhân viên chính thức,nhân viên,hà nội,1 - 2 năm,NaN,"y tế, thẩm mỹ, tiếp thị trực tuyến, làm đẹp, d...",10 tr - 25 tr vnd,10.0,25.0,vnd
18,sân bay tân sơn nhất tuyển dụng nhân viên bếp,nhân viên chính thức,nhân viên,hồ chí minh,1 - 2 năm,"phụ bếp, bếp chính, bếp trưởng, bếp phó, nhân ...","thực phẩm & đồ uống, nhà hàng, bán sỉ, bán lẻ,...","8,5 tr - 10 tr vnd",8.5,10.0,vnd
19,chuyên viên trưng bày sản phẩm,nhân viên chính thức,nhân viên,hà nội,1 - 2 năm,NaN,"marketing, bán sỉ, tiếp thị trực tuyến, bán lẻ...",10 tr - 15 tr vnd,10.0,15.0,vnd
20,quản đốc nhà máy nội thất,nhân viên chính thức,nhân viên,hà nội,1 - 3 năm,"xưởng gỗ, quản lý xưởng mộc, quản đốc nhà máy ...","quản lý điều hành, nội ngoại thất, qc), quản l...",15 tr - 30 tr vnd,15.0,30.0,vnd
21,chuyên viên phát triển thầu thợ,nhân viên chính thức,nhân viên,phú thọ,3 - 5 năm,"chuyên viên phát triển thầu thợ, business dev...","xây dựng, bán sỉ, bán lẻ, kinh doanh, bán hàng",12 tr - 20 tr vnd,12.0,20.0,vnd
22,quản lý đơn hàng quản lý đơn hàng cao cấp phòn...,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,3 - 10 năm,"kinh doanh xuất khẩu, quản lý đơn hàng, furnit...","bán sỉ, bán lẻ, xuất nhập khẩu, kinh doanh, bá...",18 tr - 35 tr vnd,18.0,35.0,vnd
23,trợ lý hệ thống sản xuất tự động,nhân viên chính thức,nhân viên,bình dương,không yêu cầu,"trợ lý điều hành kinh doanh, trợ lý kinh doanh...","dệt may, da giày, vận hành sản xuất, sản xuất,...",30 tr - 35 tr vnd,30.0,35.0,vnd
24,chuyên viên quản lý đại lý,nhân viên chính thức,nhân viên,hà nội,5 - 7 năm,"chuyên viên kinh doanh bất động sản, quản lý đ...","kinh doanh, bán hàng",15 tr - 25 tr vnd,15.0,25.0,vnd

In [4]:
# Kiểm tra thông tin cấu trúc dữ liệu
vietnam_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85470 entries, 0 to 85469
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       85463 non-null  object
 1   job_type        85470 non-null  object
 2   position_level  85470 non-null  object
 3   city            85438 non-null  object
 4   experience      85470 non-null  object
 5   skills          74176 non-null  object
 6   job_fields      77845 non-null  object
 7   salary          85470 non-null  object
 8   salary_min      85470 non-null  float64
 9   salary_max      85470 non-null  float64
 10  unit            85470 non-null  object
dtypes: float64(2), object(9)
memory usage: 7.2+ MB

In [5]:
# Đếm số dòng bị trống (Null) ở từng cột
vietnam_jobs.isnull().sum()

job_title             7
job_type              0
position_level        0
city                 32
experience            0
skills            11294
job_fields         7625
salary                0
salary_min            0
salary_max            0
unit                  0
dtype: int64

In [15]:
#Đếm số lượng bài tuyển dụng theo từng thành phố
counts = vietnam_jobs['city'].value_counts()
counts

city
hà nội                                                       26224
hồ chí minh                                                  25958
bình dương                                                    3722
đồng nai                                                      2324
hải phòng                                                     1663
                                                             ...
lô cn5a cụm công nghiệp gia lập xã gia lập huyện gia viễn        1
kcn sóng thần 1                                                  1
công ty tnhh iljin display vina                                  1
japan                                                            1
vpbank cn ba đình                                                1
Name: count, Length: 466, dtype: int64

In [16]:
counts[counts == 1]

city
lào cai\r\nhòa bình                                              1
kampong speu                                                     1
bangkok                                                          1
hòa bình\r\nbắc cạn                                              1
đồng bằng sông cửu long                                          1
champasak                                                        1
củ chi                                                           1
647 quang trung phường 11 quận gò vấp                            1
bình phước b                                                     1
54a nguyễn chí thanh                                             1
phường 19                                                        1
tuân nguyễnnguyn                                                 1
lào cai  6 nơi khác                                              1
khánh hoà                                                        1
thanh hoá  2 nơi khác                                            1
miền nam  4 nơi khác                                             1
hoà bình                                                         1
kv bắc trung bộ\r\nkv nam trung bộ\r\nđồng bằng sông cửu long    1
attapeu                                                          1
đồng bằng sông hồng                                              1
kv tây nguyên                                                    1
kratie                                                           1
phường 13 quận 10                                                1
trung văn                                                        1
phước long                                                       1
gò vấp                                                         1
lô cn5a cụm công nghiệp gia lập xã gia lập huyện gia viễn        1
kcn sóng thần 1                                                  1
công ty tnhh iljin display vina                                  1
japan                                                            1
vpbank cn ba đình                                                1
Name: count, dtype: int64

In [31]:
# Tạo một list trống tên là clean_city để chứa kết quả sạch
clean_city = []

# Dùng loop for quét qua từng dòng của cột 'city'
for dong in vietnam_jobs['city']:
    if pd.isnull(dong):
        clean_city.append('Khác')
    else:
        # Đồng nhất data type đổi thành dạng string, viết thường và xóa khoảng trắng thừa
        dong = str(dong).lower().strip()

        # Quét từ khóa để phân loại tỉnh thành
        if 'hà nội' in dong or 'ba đình' in dong or 'cầu giấy' in dong or 'hn' in dong:
            clean_city.append('Hà Nội')
        elif 'hồ chí minh' in dong or 'hcm' in dong or 'sài gòn' in dong or 'gò vấp' in dong or 'củ chi' in dong or 'quận 10' in dong or 'phường 19' in dong:
            clean_city.append('Hồ Chí Minh')
        elif 'bình dương' in dong or 'sóng thần' in dong:
            clean_city.append('Bình Dương')
        elif 'đồng nai' in dong:
            clean_city.append('Đồng Nai')
        elif 'hải phòng' in dong or 'hp' in dong:
            clean_city.append('Hải Phòng')
        elif 'công ty tnhh iljin display vina' in dong or 'hà nam' in dong:
            clean_city.append('Hà Nam')
        elif 'lô cn5a cụm công nghiệp gia lập xã gia lập huyện gia viễn' in dong or 'ninh bình' in dong:
            clean_city.append('Ninh Bình')
        elif 'lào cai' in dong:
            clean_city.append('Lào Cai')
        elif 'hoà bình' in dong:
            clean_city.append('Hòa Bình')
        elif 'khánh hoà' in dong or 'khánh hòa' in dong:
            clean_city.append('Khánh Hòa')
        elif 'thanh hoá' in dong or 'thanh hóa'in dong:
            clean_city.append('Thanh Hóa')
        elif 'bình phước' in dong:
            clean_city.append('Bình Phước')
        elif 'bắc ninh' in dong or 'bn' in dong:
            clean_city.append('Bắc Ninh')
        elif 'hải dương' in dong:
            clean_city.append('Hải Dương')
        elif 'hưng yên' in dong:
            clean_city.append('Hưng Yên')
        elif 'nam định' in dong:
            clean_city.append('Nam Định')
        elif 'thái bình' in dong:
            clean_city.append('Thái Bình')
        elif 'vĩnh phúc' in dong:
            clean_city.append('Vĩnh Phúc')
        elif 'hà giang' in dong:
            clean_city.append('Hà Giang')
        elif 'cao bằng' in dong:
            clean_city.append('Cao Bằng')
        elif 'bắc kạn' in dong or 'bắc cạn' in dong:
            clean_city.append('Bắc Kạn')
        elif 'tuyên quang' in dong:
            clean_city.append('Tuyên Quang')
        elif 'lạng sơn' in dong:
            clean_city.append('Lạng Sơn')
        elif 'quảng ninh' in dong:
            clean_city.append('Quảng Ninh')
        elif 'bắc giang' in dong:
            clean_city.append('Bắc Giang')
        elif 'phú thọ' in dong:
            clean_city.append('Phú Thọ')
        elif 'thái nguyên' in dong:
            clean_city.append('Thái Nguyên')
        elif 'yên bái' in dong:
            clean_city.append('Yên Bái')
        elif 'điện biên' in dong:
            clean_city.append('Điện Biên')
        elif 'lai châu' in dong:
            clean_city.append('Lai Châu')
        elif 'sơn la' in dong:
            clean_city.append('Sơn La')
        elif 'nghệ an' in dong:
            clean_city.append('Nghệ An')
        elif 'hà tĩnh' in dong:
            clean_city.append('Hà Tĩnh')
        elif 'quảng bình' in dong:
            clean_city.append('Quảng Bình')
        elif 'quảng trị' in dong:
            clean_city.append('Quảng Trị')
        elif 'thừa thiên huế' in dong or 'huế' in dong:
            clean_city.append('Thừa Thiên Huế')
        elif 'đà nẵng' in dong or 'đn' in dong:
            clean_city.append('Đà Nẵng')
        elif 'quảng nam' in dong:
            clean_city.append('Quảng Nam')
        elif 'quảng ngãi' in dong:
            clean_city.append('Quảng Ngãi')
        elif 'bình định' in dong or 'quy nhơn' in dong:
            clean_city.append('Bình Định')
        elif 'phú yên' in dong:
            clean_city.append('Phú Yên')
        elif 'ninh thuận' in dong:
            clean_city.append('Ninh Thuận')
        elif 'bình thuận' in dong:
            clean_city.append('Bình Thuận')
        elif 'kon tum' in dong:
            clean_city.append('Kon Tum')
        elif 'gia lai' in dong:
            clean_city.append('Gia Lai')
        elif 'đắk lắk' in dong or 'đắc lắc' in dong or 'dak lak' in dong:
            clean_city.append('Đắk Lắk')
        elif 'đắk nông' in dong or 'đắc nông' in dong or 'dak nong' in dong:
            clean_city.append('Đắk Nông')
        elif 'lâm đồng' in dong or 'đà lạt' in dong:
            clean_city.append('Lâm Đồng')
        elif 'bình dương' in dong:
            clean_city.append('Bình Dương')
        elif 'đồng nai' in dong:
            clean_city.append('Đồng Nai')
        elif 'tây ninh' in dong:
            clean_city.append('Tây Ninh')
        elif 'bà rịa' in dong or 'vũng tàu' in dong or 'brvt' in dong:
            clean_city.append('Bà Rịa - Vũng Tàu')
        elif 'long an' in dong:
            clean_city.append('Long An')
        elif 'tiền giang' in dong:
            clean_city.append('Tiền Giang')
        elif 'bến tre' in dong:
            clean_city.append('Bến Tre')
        elif 'trà vinh' in dong:
            clean_city.append('Trà Vinh')
        elif 'vĩnh long' in dong:
            clean_city.append('Vĩnh Long')
        elif 'đồng tháp' in dong:
            clean_city.append('Đồng Tháp')
        elif 'an giang' in dong:
            clean_city.append('An Giang')
        elif 'kiên giang' in dong:
            clean_city.append('Kiên Giang')
        elif 'cần thơ' in dong or 'ct' in dong:
            clean_city.append('Cần Thơ')
        elif 'hậu giang' in dong:
            clean_city.append('Hậu Giang')
        elif 'sóc trăng' in dong:
            clean_city.append('Sóc Trăng')
        elif 'bạc liêu' in dong:
            clean_city.append('Bạc Liêu')
        elif 'cà mau' in dong:
            clean_city.append('Cà Mau')
        else:
            clean_city.append('Khác')

# Tạo cột mới 'city_clean' từ danh sách clean_city đã làm sạch
vietnam_jobs['city_clean'] = clean_city

# Xem kết quả sau khi phân loại
vietnam_jobs['city_clean'].value_counts()

city_clean
Hà Nội         26377
Hồ Chí Minh    26041
Khác            5150
Bình Dương      3723
Đồng Nai        2324
               ...
Quảng Trị         42
Trà Vinh          42
Bắc Kạn           40
Lai Châu          33
Hòa Bình           9
Name: count, Length: 64, dtype: int64

In [33]:
#check lại cột city đã chuẩn xác lại hay chưa
vietnam_jobs[vietnam_jobs['city_clean'] == 'Khác']

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit,city_clean
26,quản lý cửa hàng,nhân viên chính thức,nhân viên,toàn quốc,lên đến 1 năm,NaN,"bán sỉ, bán hàng, bán lẻ, kinh doanh",trên 12 tr vnd,12.0,0.0,vnd,Khác
269,nhân viên quầy thu ngân cashier operator,nhân viên chính thức,nhân viên,quốc tế,1 - 2 năm,NaN,"khách sạn, du lịch, nhà hàng",18 tr - 40 tr vnd,18.0,40.0,vnd,Khác
313,nhân viên kế toán thanh toán,nhân viên chính thức,nhân viên,attapeu,trên 2 năm,nhân viên kế toán thanh toán làm việc tại lào,"kế toán, kiểm toán",10 tr - 12 tr vnd,10.0,12.0,vnd,Khác
1281,nhân viên telesales,nhân viên chính thức,nhân viên,toàn quốc,lên đến 1 năm,"sales executive, nhân viên telesales, sales re...","dược phẩm, bán sỉ, hóa mỹ phẩm, bán lẻ, kinh d...",15 tr - 25 tr vnd,15.0,25.0,vnd,Khác
1480,việt phi chuyên viên kế toán làm việc tại châu...,nhân viên chính thức,nhân viên,khác,trên 3 năm,"accountant, kế toán viên, junior accountant, v...","kế toán, kiểm toán",20 tr - 30 tr vnd,20.0,30.0,vnd,Khác
...,...,...,...,...,...,...,...,...,...,...,...,...
85098,nhân viên telesale sản phẩm thẻ tín dụng ngân ...,full-time,"nhân viên, chuyên viên",hà hội,không yêu cầu,"bán hàng qua điện thoại (telesale), tư vấn bán...",NaN,8 - 20 triệu vnđ,8.0,20.0,vnd,Khác
85178,cán bộ kỹ thuật,toàn thời gian,nhân viên,miền bắc,không yêu cầu kinh nghiệm,NaN,NaN,10 - 20 triệu,10.0,20.0,vnd,Khác
85364,nhân viên thống kê trang trại,nhân viên chính thức,nhân viên,toàn quốc,không yêu cầu,NaN,NaN,11 tr - 13 tr vnd,11.0,13.0,vnd,Khác
85370,quản lý trang trại,nhân viên chính thức,quản lý,toàn quốc,2 - 5 năm,NaN,NaN,17 tr - 30 tr vnd,17.0,30.0,vnd,Khác
85465,bảo trì trang trại,nhân viên chính thức,nhân viên,toàn quốc,không yêu cầu,NaN,NaN,10 tr - 15 tr vnd,10.0,15.0,vnd,Khác

In [26]:
#check giá trị của cột unit
vietnam_jobs['unit'].value_counts()

unit
vnd    84757
usd      713
Name: count, dtype: int64

In [34]:
#những JD để đơn vị lương là usd
vietnam_jobs[vietnam_jobs['unit'] == 'usd']

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit,city_clean
3,home textile designer,nhân viên chính thức,nhân viên,hưng yên,5 - 15 năm,NaN,"dệt may, nghệ thuật, da giày, thiết kế, mỹ thu...","800 - 1,500 usd",20.0,37.5,usd,Hưng Yên
60,senior fabric technician,nhân viên chính thức,nhân viên,quảng ngãi,3 - 5 năm,"knitting techincal, jabil, senior fabric techn...","dệt may, da giày, thời trang","1,200 - 1,200 usd",30.0,30.0,usd,Quảng Ngãi
100,nhân viên phát triển nông học khu vực thanh hó...,nhân viên chính thức,nhân viên,thanh hóa,2 - 10 năm,"kỹ sư trồng trọt, kỹ thuật nông học, nhân viên...","thực phẩm & đồ uống, nông nghiệp",100 - 500 usd,2.5,12.5,usd,Thanh Hóa
104,hiệu phó các cấp tiểu học thcs thpt,nhân viên chính thức,quản lý,hà nội,3 - 5 năm,"hiệu trưởng, hiệu phó, quản lý giáo dục, giáo ...","quản lý điều hành, giáo dục, đào tạo","1,000 - 2,000 usd",25.0,50.0,usd,Hà Nội
124,production manager,nhân viên chính thức,quản lý,sóc trăng,5 - 7 năm,"quản đốc sản xuất, production manager hand bag...","dệt may, da giày, vận hành sản xuất, sản xuất,...","trên 4,000 usd",100.0,0.0,usd,Sóc Trăng
...,...,...,...,...,...,...,...,...,...,...,...,...
85277,biên tập nội dung,toàn thời gian,nhân viên,hà nội,2 năm,NaN,NaN,"tới 1,000 usd",25.0,0.0,usd,Hà Nội
85353,back end developer,nhân viên chính thức,nhân viên,hồ chí minh,3 - 5 năm,NaN,NaN,"3,000 - 5,000 usd",75.0,125.0,usd,Hồ Chí Minh
85368,backend developer,nhân viên chính thức,nhân viên,hà nội,3 - 10 năm,NaN,NaN,"1,000 - 1,600 usd",25.0,40.0,usd,Hà Nội
85429,brand manager,nhân viên chính thức,quản lý,hồ chí minh,lên đến 15 năm,"trưởng nhãn hàng, senior brand manager, brand ...",NaN,"3,000 - 4,000 usd",75.0,100.0,usd,Hồ Chí Minh
85453,brand manager,nhân viên chính thức,quản lý,hà nội,lên đến 4 năm,"trưởng nhãn hàng, senior brand manager, giám đ...",NaN,"1,000 - 1,500 usd",25.0,37.5,usd,Hà Nội